services:
  hausarbeit:
    image: hausarbeit
    build:
      context: ./db-sqlAlchemy-alembic
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8000:8000
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
