name: kundendokumentation_builder
description: "Kundendokumentation-Builder mit Bild- und Daten-Upload"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  firebase_performance: ^0.10.1+7
  cloud_firestore: ^5.6.9
  http: ^1.4.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.6
  firebase_auth_mocks: ^0.14.2
  fake_cloud_firestore: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
