"""Initiales Datenbankmodell

Revision ID: b7f50e694365
Revises: 22c995e6969f
Create Date: 2025-06-22 12:33:28.672209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f50e694365'
down_revision: Union[str, None] = '22c995e6969f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kunden_id'), table_name='kunden')
    op.drop_table('kunden')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kunden',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('kunden_pkey'))
    )
    op.create_index(op.f('ix_kunden_id'), 'kunden', ['id'], unique=False)
    # ### end Alembic commands ###
