"""fixed migration gesamt db

Revision ID: cb5e54c2662d
Revises: 
Create Date: 2025-06-30 16:45:45.218409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5e54c2662d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kunden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kunden_id'), 'kunden', ['id'], unique=False)
    op.create_table('standorte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('kunde_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunden.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standorte_id'), 'standorte', ['id'], unique=False)
    op.create_table('abteilungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('standort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['standort_id'], ['standorte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abteilungen_id'), 'abteilungen', ['id'], unique=False)
    op.create_table('anlagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abteilung_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abteilung_id'], ['abteilungen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anlagen_id'), 'anlagen', ['id'], unique=False)
    op.create_table('berichte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('anlage_id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('nutzer_name', sa.String(), nullable=True),
    sa.Column('nutzer_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anlage_id'], ['anlagen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berichte_id'), 'berichte', ['id'], unique=False)
    op.create_table('eintraege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('wert', sa.String(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('bericht_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bericht_id'], ['berichte.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eintraege_id'), 'eintraege', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eintraege_id'), table_name='eintraege')
    op.drop_table('eintraege')
    op.drop_index(op.f('ix_berichte_id'), table_name='berichte')
    op.drop_table('berichte')
    op.drop_index(op.f('ix_anlagen_id'), table_name='anlagen')
    op.drop_table('anlagen')
    op.drop_index(op.f('ix_abteilungen_id'), table_name='abteilungen')
    op.drop_table('abteilungen')
    op.drop_index(op.f('ix_standorte_id'), table_name='standorte')
    op.drop_table('standorte')
    op.drop_index(op.f('ix_kunden_id'), table_name='kunden')
    op.drop_table('kunden')
    # ### end Alembic commands ###
