"""fixed bericht struktur

Revision ID: ffc1caced433
Revises: 5da7d1398810
Create Date: 2025-06-30 18:26:36.050187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc1caced433'
down_revision: Union[str, None] = '5da7d1398810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('berichte', 'beschreibung',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('berichte', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('berichte', 'erstellt_am',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('berichte', 'beschreibung',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
