name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Linter
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          autofix: false